pipeline {
    agent any
    stages {
        stage('Build & Test ') {
            steps {
                script {
                    // change to the directory where the pom.xml is
                    dir('apiDemo') {
                        docker.image('maven:3.8.6-eclipse-temurin-17').inside('-v /root/.m2:/root/.m2') {
                            sh 'mvn clean package'
                        }
                    }
                }
                sh 'echo "adding one step"'
            }
        }
        stage('Docker Deploy') {
            steps {
                script {
                    // change to the directory where the Dockerfile is
                    dir('apiDemo') {
                        sh '''
                            docker stop api-demo-live || true
                            docker rm api-demo-live || true
                            docker build -t api-demo-jenkins .
                            docker run -d -p 8090:8090 --name api-demo-live api-demo-jenkins
                        '''
                    }
                }
            }
        }
    }
}